# Generated by Django 5.2.13 on 2026-04-11 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predictions', '0001_initial'),
        ('sensor_ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('STORM_PROBABILITY', 'Storm Probability'), ('PRESSURE_HIGH', 'Pressure High'), ('PRESSURE_LOW', 'Pressure Low'), ('TEMPERATURE_HIGH', 'Temperature High'), ('TEMPERATURE_LOW', 'Temperature Low')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('threshold_value', models.FloatField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('cooldown_minutes', models.IntegerField(default=30)),
                ('message_template', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(max_length=30)),
                ('severity', models.CharField(max_length=10)),
                ('triggered_value', models.FloatField()),
                ('threshold_value', models.FloatField()),
                ('message', models.TextField()),
                ('whatsapp_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('MANUAL_CHECK_NEEDED', 'Manual Check Needed')], default='PENDING', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='predictions.prediction')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor_ingest.sensorreading')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alerting.alertrule')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='alerting_al_created_3700fe_idx'), models.Index(fields=['rule_type'], name='alerting_al_rule_ty_45c4ec_idx'), models.Index(fields=['whatsapp_status'], name='alerting_al_whatsap_57dd3b_idx'), models.Index(fields=['rule_type', 'created_at'], name='alerting_al_rule_ty_ec4b78_idx')],
            },
        ),
    ]
