# Generated by Django 5.2.13 on 2026-04-11 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppRuntimeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_ready', models.BooleanField(default=False)),
                ('last_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Runtime Status',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('MANUAL_CHECK_NEEDED', 'Manual Check Needed')], max_length=25)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('is_test', models.BooleanField(default=False)),
                ('alert_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alerting.alertevent')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp_integration.whatsapprecipient')),
            ],
            options={
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['attempted_at'], name='whatsapp_in_attempt_48aa04_idx'), models.Index(fields=['status'], name='whatsapp_in_status_83e17c_idx')],
            },
        ),
    ]
