# Generated by Django 5.2.13 on 2026-04-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('pressure_hpa', models.FloatField()),
                ('temperature_c', models.FloatField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('sensor', 'Sensor'), ('simulator', 'Simulator'), ('manual', 'Manual')], default='sensor', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='sensor_inge_timesta_439c6f_idx'), models.Index(fields=['timestamp', 'source'], name='sensor_inge_timesta_a22ac2_idx')],
            },
        ),
    ]
